- name: Install Debian packages
  package:
    name:
      - php7.3-curl
      - php7.3-intl
      - php7.3-gd
      - php7.3-mysql
      - php7.3-dev
      - php7.3-mbstring
      - php7.3-fpm
      - php-gnupg
      - composer
      - gnupg
    state: present
  when: ansible_os_family == 'Debian'
  tags:
    - passbolt
    - passbolt-package

- name: Install entropy helper if instance is a guest
  package:
    name: haveged
    state: present
  when: ansible_virtualization_type is defined and ansible_virtualization_type in ["docker", "kvm"]
  tags:
    - passbolt-packages
    - passbolt-gpg
